export default {
    'GET_EVENTS': 'GET_EVENTS',
    'LOAD_MORE_EVENTS': 'LOAD_MORE_EVENTS',
    'LOADING_EVENTS': 'LOADING_EVENTS',
    'WAITING_EVENTS': 'WAITING_EVENTS',
    'DONE_EVENTS': 'DONE_EVENTS'
}